### PR TITLE
Twice error case

### PR DESCRIPTION
**Pull request by kuraga**
@zensh , why?

### CODE REVIEW

**Comment by kuraga** [comment]
Thanks! Sorry about several commits... I didn't mind to merge...

The most interesting that creating a _new_ `Trie` doesn't help!

``` js
it('twice error case', function () {
  var trie = new Trie()
  try {
    trie.define('///')
  } catch (e) {}

  var trie_new = new Trie()
  assert.throws(function () {
    trie_new.define('///')
  }, null, 'Multi-slash exist.')
})
```

**Comment by zensh** [comment]
It is caused by `multiSlashReg` bug~

**Comment by kuraga** [comment]
Hm... Can you explain the fix, please?

**Comment by zensh** [comment]
``` js
var r = /(\/){2,}/g
r.test('///') // true
r.lastIndex // 3
r.test('///') // false
r.lastIndex // 0
r.test('///') // true
r.lastIndex // 3
```

**Comment by kuraga** [comment]
Ahaa, `multiSlashReg` is common (global)... Thanks!

P.S. What about other regular expression variables?

**Pull request merged**
