### PR TITLE
Add empty name test

### PR DESCRIPTION
**Pull request by kuraga**
@zensh , need?

### CODE REVIEW

**Comment by zensh** [comment]
Yes, it should be fixed

**Comment by zensh** [comment]
Hi, I have remove this test case. I think `/abc/:/xyz` should be matched as `/abc/:/xyz`. Some web site will use `:` in URL, here https://github.com/cnpm/cnpmjs.org/blob/master/routes/registry.js#L109

**Comment by zensh** [comment]
`v1.1.1` released for simple fixed.

I will improve code to require strict regulation in router expression.

**Comment by kuraga** [comment]
Thanks! Just think we need to add a test case for `/abc/:/xyz`, etc, then...

**Comment by kuraga** [comment]
@zensh , as I see we forbid `:` without named expression (`:name`) or end of chunk (i.e. `/`) after. Mention this in docs and tests?

**Pull request merged**
